version: '3.8'
services:
  app:
    container_name: app
    build: .
    ports:
      - "9999:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cinema
      SWAGGER_SERVER_URL: http://localhost:9999
    depends_on:
      - db
    restart: always

  db:
    container_name: db
    image: postgres:12-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: cinema
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
    restart: always
